name: ci

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  test:
    uses: upfluence/private-actions/.github/workflows/lib-go-test.yml@master
    secrets: inherit
    with:
      go-version-matrix: "['1.20.x', '1.21.x', '1.23.x']"

  release:
    needs: test
    if: github.ref == 'refs/heads/master'
    uses: upfluence/actions/.github/workflows/lib-any-release.yml@master
    secrets: inherit
