name: ci

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    uses: upfluence/actions/.github/workflows/lib-go-test.yml@master
    secrets: inherit

  release:
    needs: test
    if: github.ref == 'refs/heads/master'
    uses: upfluence/actions/.github/workflows/lib-any-release.yml@master
    secrets: inherit
